### ISSUE TITLE
UnitTest custom MiddleWare

### ISSUE THREAD

**Issue by nuke-dash** [ReSwift/ReactiveReSwift#10]
The `transform` property of `MiddleWare` is set to internal.
This prevents you from unit testing the `MiddleWare` you wrote.
![screen shot 2017-03-17 at 14 35 15](https://cloud.githubusercontent.com/assets/6998635/24045326/f596f2d2-0b1e-11e7-9368-4ef0467911c8.png)
Could this be made public?

**Comment by nuke-dash** [comment]
I could also create a Store and add the middleware to that and then send to actions to the Store.
But that seems a bit unnecessary.

**Comment by Qata** [comment]
@Nuke- Can't you use `@testable import` on ReactiveReSwift?

**Comment by nuke-dash** [comment]
Sorry, I didn't thought of that.
That made it work.
Thanks.
