### ISSUE TITLE
ReSwift vs ReactiveReSwift

### ISSUE THREAD

**Issue by rpassis** [ReSwift/ReactiveReSwift#12]
Hi guys,

I just came across this Reactive version of ReSwift and the main question I had while reading the documentation is what are the main benefits of using it instead of the plain vanilla ReSwift? 

Admittedly I have very little experience with FRP but as far as I can see the main difference between the two libraries is in the way we can subscribe to state updates? Are there any advantages between one over the other?

Thanks!
Rog

**Comment by Qata** [comment]
The advantages lie mostly in FRP. I suggest learning about that.
