### ISSUE TITLE
New release for swift 4?

### ISSUE THREAD

**Issue by alickbass** [ReSwift/ReactiveReSwift#16]
Hi! I noticed, that in master there is code for swift 4, but there has been no tag for that. Is it just a matter of drafting a new release? Or is there any extra work that needs to be done? I could help with that

**Comment by Qata** [comment]
Release done!

**Comment by monday8am** [comment]
but just for Carthage, Cocoapods is still outdated :(

**Comment by Qata** [comment]
@monday8am Sorry about that, should now be fixed. Let me know if it isn't.
