### ISSUE TITLE
dispatch<S: StreamType>(_ stream: S) leaks hot observables

### ISSUE THREAD

**Issue by guitcastro** [ReSwift/ReactiveReSwift#20]
If we have a hot observable that produces actions, like `let actionSource = Observable<Action>` and we use `store.dispatch(actionSource)` there is no way to unsubscribe/dispose the observable causing a leak.

We need something function that dispatch the observable and return the `SubscriptionReferenceType` so we can unsubscribe when necessary.

As a workaround, I am using this extension function:
```

extension Store where ObservableProperty == Variable<AppState> {
    func dispatchWithDisposable<S: StreamType>(_ stream: S) where S.ValueType: Action -> SubscriptionReferenceType {
        return stream.subscribe({ [unowned self] action in
            self.dispatch(action)
        })
    }
} 
```

Although I think we need a more descriptive name or even remove/deprecate the old dispatch function in order to use the new one, and create an extension function for stream that add the subscription to the Store. Something like this:

```
store.dispatch(actionSource)
     .disposeByStore(store)
```

**Comment by Qata** [comment]
Just created a release that now returns an optional subscription reference from `dispatch`.

**Comment by guitcastro** [comment]
Perfect! thanks very much ;)
