### ISSUE TITLE
CocoaPods installation

### ISSUE THREAD

**Issue by vadymmarkov** [ReSwift/ReactiveReSwift#5]
Is there any reason why the library doesn't have a Podspec and is not released on CocoaPods yet?

**Comment by Qata** [comment]
It's currently still a pre-release. Once I'm happy with the library I'll mark a release as live and add it to CocoaPods.

**Comment by Qata** [comment]
This will probably be soon, possibly before next week.

**Comment by vadymmarkov** [comment]
@Qata Great news, thank you!

**Comment by Qata** [comment]
@vadymmarkov If you want to create a PR for your branch then I'll gladly merge it.

**Comment by vadymmarkov** [comment]
@Qata Here you go 😉 https://github.com/ReSwift/ReactiveReSwift/pull/6

**Comment by vadymmarkov** [comment]
I think we can close it now.
