### ISSUE TITLE
Combined reducer not possible?

### ISSUE THREAD

**Issue by nuke-dash** [ReSwift/ReactiveReSwift#7]
How do you create a combined reducer?
Because the transform var of a reducer is set to internal it doesn't seem possible.
Or am I missing something?

![screen shot 2017-02-15 at 17 49 33](https://cloud.githubusercontent.com/assets/6998635/22985090/ab03e466-f3a7-11e6-9d6d-43ac84345769.png)

**Comment by Qata** [comment]
@Nuke- at the moment you can't nest Reducers vertically, you have to use map to transform your reducer. I've been meaning to fix that so I'll get to that today if possible.

**Comment by Qata** [comment]
Fixed in 3.0.4

**Comment by Qata** [comment]
I'm also going to do a breaking change for the 3.0.5 release and change `Reducer` to just a function alias, like in ReSwift. I don't think being able to chain `Reducer`s is helping as much as it's hindering.
