### ISSUE TITLE
Dispatch async action in MiddleWare

### ISSUE THREAD

**Issue by nuke-dash** [ReSwift/ReactiveReSwift#8]
If you do an async operation in the MiddleWare you want to post the result as an action to the store.
But the store is not one of the incoming variables?
Or should you just use the dispatch method.
But that doesn't work currently as it is not marked as @escaped so you cannot use it to dispatch an action async.

**Comment by Qata** [comment]
I'll look into this.

**Comment by Qata** [comment]
This is fixed in 7a4b42e and will be in the next release.
